"""followers

Revision ID: 401c7ec2fef9
Revises: 716542a62ff0
Create Date: 2021-04-15 10:19:18.635812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401c7ec2fef9'
down_revision = '716542a62ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
